/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.UsuariosDao;
import entity.Usuarios;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author WingedWarlock
 */
public class CadastrarUsuarios2_1 extends javax.swing.JDialog {

    /**
     * Creates new form CadastrarUsuarios
     */
    public CadastrarUsuarios2_1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.addComponentListener(new ComponentAdapter() {

public void componentMoved(ComponentEvent e) {

setEnabled(false);

setEnabled(true);

}

});
        iniciarBD();
        primeiro();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNome = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JTextField();
        tfData = new javax.swing.JTextField();
        tfHora = new javax.swing.JTextField();
        tfLogin = new javax.swing.JTextField();
        tfSenha = new javax.swing.JTextField();
        jLabelCpf = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jLabelGerenciarUsuarios = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        tfCpf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(tfNome);
        tfNome.setBounds(260, 30, 120, 27);
        getContentPane().add(tfTelefone);
        tfTelefone.setBounds(90, 60, 110, 27);
        getContentPane().add(tfData);
        tfData.setBounds(260, 60, 120, 27);
        getContentPane().add(tfHora);
        tfHora.setBounds(70, 90, 130, 27);
        getContentPane().add(tfLogin);
        tfLogin.setBounds(260, 90, 120, 27);
        getContentPane().add(tfSenha);
        tfSenha.setBounds(80, 120, 120, 27);

        jLabelCpf.setText("Cpf");
        getContentPane().add(jLabelCpf);
        jLabelCpf.setBounds(40, 30, 100, 27);

        jLabelNome.setText("Nome");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(227, 30, 90, 27);

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Add.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setMaximumSize(new java.awt.Dimension(180, 70));
        jButtonLimpar.setMinimumSize(new java.awt.Dimension(180, 70));
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(10, 210, 120, 50);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/salvar.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setMaximumSize(new java.awt.Dimension(180, 70));
        jButtonSalvar.setMinimumSize(new java.awt.Dimension(180, 70));
        jButtonSalvar.setPreferredSize(new java.awt.Dimension(101, 49));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(140, 200, 130, 70);

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/excluir.jpg"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setMaximumSize(new java.awt.Dimension(180, 70));
        jButtonExcluir.setMinimumSize(new java.awt.Dimension(180, 70));
        jButtonExcluir.setPreferredSize(new java.awt.Dimension(180, 70));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(280, 210, 110, 50);

        jLabelTelefone.setText("Telefone");
        getContentPane().add(jLabelTelefone);
        jLabelTelefone.setBounds(40, 60, 110, 27);

        jLabelData.setText("Data");
        getContentPane().add(jLabelData);
        jLabelData.setBounds(230, 60, 110, 27);

        jLabelHora.setText("Hora");
        getContentPane().add(jLabelHora);
        jLabelHora.setBounds(40, 90, 90, 27);

        jLabelLogin.setText("Login");
        getContentPane().add(jLabelLogin);
        jLabelLogin.setBounds(230, 90, 90, 27);

        jLabelSenha.setText("Senha");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(40, 120, 90, 27);

        jLabelGerenciarUsuarios.setText("Gerenciar Usuários");
        getContentPane().add(jLabelGerenciarUsuarios);
        jLabelGerenciarUsuarios.setBounds(140, 0, 130, 27);

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/find.jpg"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(20, 150, 140, 40);
        getContentPane().add(tfCpf);
        tfCpf.setBounds(70, 30, 130, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        tfCpf.setText( "" );
        tfNome.setText( "" );
        tfTelefone.setText( "" );
        tfData.setText( "" );
        tfHora.setText( "" );
        tfLogin.setText( "" );
        tfSenha.setText( "" );
        tfCpf.requestFocus();  
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        try {
            int cpf = Integer.parseInt( tfCpf.getText() );  
            String nome = tfNome.getText(); 
            String telefone = tfTelefone.getText();
            String data = tfData.getText();
            String hora = tfHora.getText();
            String login = tfLogin.getText();
            String senha = tfSenha.getText();
            Usuarios usuarios = new Usuarios();
            usuarios.setCpf( cpf );
            usuarios.setNome( nome );
            usuarios.setTelefone( telefone );
            usuarios.setData( data );
            usuarios.setHora( hora );
            usuarios.setLogin( login );
            usuarios.setSenha( senha );
            usuariosDao.salvarRegistro( usuarios );
            JOptionPane.showMessageDialog( this, "Sucesso" );
                        
            } catch ( SQLException e1 ) {
               JOptionPane.showMessageDialog( this, "Erro: " + e1.getMessage() ); 
            }       
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        String cpf = tfCpf.getText();  
         
        try {
            usuariosDao.excluirRegistro( Integer.parseInt( cpf ) );
            JOptionPane.showMessageDialog( this, "Sucesso" );
        } catch ( SQLException e) {
            JOptionPane.showMessageDialog( this, "Erro: " + e.getMessage() );
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
         try {
                int cpf = Integer.parseInt( JOptionPane.showInputDialog( this, "Digite o cpf a pesquisar") );

                Usuarios usuarios = usuariosDao.pesquisarUsuarios( cpf );

                if ( usuarios != null ) {
                    mostrarDados( usuarios );                    
                    JOptionPane.showMessageDialog( this, "Registro Encontrado." );
                    tfLogin.setText( "" );
                    tfSenha.setText( "" );
                } else {
                    JOptionPane.showMessageDialog( this, "Registro Não Encontrado ");
                }
        } catch ( SQLException e ) {
            JOptionPane.showMessageDialog( this, "Erro: " + e.getMessage() );
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuarios2_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuarios2_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuarios2_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuarios2_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            CadastrarUsuarios2_1 dialog = new CadastrarUsuarios2_1(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
            }
        });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelGerenciarUsuarios;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JTextField tfCpf;
    private javax.swing.JTextField tfData;
    private javax.swing.JTextField tfHora;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfSenha;
    private javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
    private java.sql.Connection con;
    private java.sql.Statement stmt;
    private java.sql.Statement stmtNavegar;
    private java.sql.ResultSet rsNavegar;
    private dao.UsuariosDao usuariosDao;
    
    private void iniciarBD() {
        
        
        try {
            usuariosDao = new UsuariosDao();
        } catch ( Exception e ) {
            JOptionPane.showMessageDialog( this, "Erro: " + e.getMessage() );
        }
    }
   public void mostrarDados( Usuarios usuarios ) {
        tfCpf.setText( String.valueOf( usuarios.getCpf() ) );
        tfNome.setText( String.valueOf( usuarios.getNome() ) );
        tfTelefone.setText( String.valueOf( usuarios.getTelefone() ) );
        tfData.setText( String.valueOf( usuarios.getData() ) );
        tfHora.setText( String.valueOf( usuarios.getHora() ) );
        tfLogin.setText( "" );
        tfSenha.setText( "" );
    }
    public void primeiro() {
        try {
                Usuarios usuarios = usuariosDao.primeiro();

                if ( usuarios != null) {
                    mostrarDados( usuarios );
                }                    
            
        } catch ( SQLException e ) {
            JOptionPane.showMessageDialog( this, "Erro: " + e.getMessage() );
        }
    }
  
}

