/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ClientesDao;
import entity.Clientes;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author WingedWarlock
 */
public class CadastrarClientes extends javax.swing.JDialog {

    /**
     * Creates new form CadastrarClientes
     */
    public CadastrarClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.addComponentListener(new ComponentAdapter() {

public void componentMoved(ComponentEvent e) {

setEnabled(false);

setEnabled(true);

}

});
        iniciarBD();
        primeiro();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNome = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JTextField();
        tfData = new javax.swing.JTextField();
        tfHora = new javax.swing.JTextField();
        tfPeso = new javax.swing.JTextField();
        tfMassa = new javax.swing.JTextField();
        jLabelCpf = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jLabelLog = new javax.swing.JLabel();
        jLabelMassa = new javax.swing.JLabel();
        jLabelGerenciarUsuarios = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        tfCpf = new javax.swing.JTextField();
        tfGordura = new javax.swing.JTextField();
        jLabelGordura1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(tfNome);
        tfNome.setBounds(260, 30, 120, 27);
        getContentPane().add(tfTelefone);
        tfTelefone.setBounds(90, 60, 110, 27);
        getContentPane().add(tfData);
        tfData.setBounds(260, 60, 120, 27);
        getContentPane().add(tfHora);
        tfHora.setBounds(70, 90, 130, 27);
        getContentPane().add(tfPeso);
        tfPeso.setBounds(260, 90, 120, 27);
        getContentPane().add(tfMassa);
        tfMassa.setBounds(270, 120, 110, 27);

        jLabelCpf.setText("Cpf");
        getContentPane().add(jLabelCpf);
        jLabelCpf.setBounds(40, 30, 100, 27);

        jLabelNome.setText("Nome");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(227, 30, 90, 27);

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Add.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setMaximumSize(new java.awt.Dimension(180, 70));
        jButtonLimpar.setMinimumSize(new java.awt.Dimension(180, 70));
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(10, 210, 120, 50);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/salvar.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setMaximumSize(new java.awt.Dimension(180, 70));
        jButtonSalvar.setMinimumSize(new java.awt.Dimension(180, 70));
        jButtonSalvar.setPreferredSize(new java.awt.Dimension(101, 49));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(140, 200, 130, 70);

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/excluir.jpg"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setMaximumSize(new java.awt.Dimension(180, 70));
        jButtonExcluir.setMinimumSize(new java.awt.Dimension(180, 70));
        jButtonExcluir.setPreferredSize(new java.awt.Dimension(180, 70));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(280, 210, 110, 50);

        jLabelTelefone.setText("Telefone");
        getContentPane().add(jLabelTelefone);
        jLabelTelefone.setBounds(40, 60, 110, 27);

        jLabelData.setText("Data");
        getContentPane().add(jLabelData);
        jLabelData.setBounds(230, 60, 110, 27);

        jLabelHora.setText("Hora");
        getContentPane().add(jLabelHora);
        jLabelHora.setBounds(40, 90, 90, 27);

        jLabelLog.setText("Peso");
        getContentPane().add(jLabelLog);
        jLabelLog.setBounds(230, 90, 90, 27);

        jLabelMassa.setText("Massa");
        getContentPane().add(jLabelMassa);
        jLabelMassa.setBounds(230, 120, 90, 27);

        jLabelGerenciarUsuarios.setText("Gerenciar Clientes");
        getContentPane().add(jLabelGerenciarUsuarios);
        jLabelGerenciarUsuarios.setBounds(140, 0, 130, 27);

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/find.jpg"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(20, 150, 140, 40);
        getContentPane().add(tfCpf);
        tfCpf.setBounds(70, 30, 130, 27);
        getContentPane().add(tfGordura);
        tfGordura.setBounds(90, 120, 110, 27);

        jLabelGordura1.setText("Gordura");
        getContentPane().add(jLabelGordura1);
        jLabelGordura1.setBounds(40, 120, 90, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        tfCpf.setText( "" );
        tfNome.setText( "" );
        tfTelefone.setText( "" );
        tfData.setText( "" );
        tfHora.setText( "" );
        tfPeso.setText( "" );
        tfGordura.setText( "" );
        tfMassa.setText( "" );
        tfCpf.requestFocus();  
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        try {
            int cpf = Integer.parseInt( tfCpf.getText() );  
            String nome = tfNome.getText(); 
            String telefone = tfTelefone.getText();
            String data = tfData.getText();
            String hora = tfHora.getText();
            float peso = Float.parseFloat(tfPeso.getText());
            float gordura = Float.parseFloat(tfGordura.getText());
            float massa = Float.parseFloat(tfMassa.getText());
            Clientes clientes = new Clientes();
            clientes.setCpf( cpf );
            clientes.setNome( nome );
            clientes.setTelefone( telefone );
            clientes.setData( data );
            clientes.setHora( hora );
            clientes.setPeso( peso );
            clientes.setGordura( gordura );
            clientes.setMassa( massa );
            clientesDao.salvarRegistro( clientes );
            JOptionPane.showMessageDialog( this, "Sucesso" );
                        
            } catch ( SQLException e1 ) {
               JOptionPane.showMessageDialog( this, "Erro: " + e1.getMessage() ); 
            }       
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        String cpf = tfCpf.getText();  
         
        try {
            clientesDao.excluirRegistro( Integer.parseInt( cpf ) );
            JOptionPane.showMessageDialog( this, "Sucesso" );
        } catch ( SQLException e) {
            JOptionPane.showMessageDialog( this, "Erro: " + e.getMessage() );
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
         try {
                int cpf = Integer.parseInt( JOptionPane.showInputDialog( this, "Digite o cpf a pesquisar") );

                Clientes clientes = clientesDao.pesquisarClientes( cpf );

                if ( clientes != null ) {
                    mostrarDados( clientes );                    
                    JOptionPane.showMessageDialog( this, "Registro Encontrado." );
                } else {
                    JOptionPane.showMessageDialog( this, "Registro Não Encontrado ");
                }
        } catch ( SQLException e ) {
            JOptionPane.showMessageDialog( this, "Erro: " + e.getMessage() );
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            CadastrarClientes dialog = new CadastrarClientes(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
            }
        });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelGerenciarUsuarios;
    private javax.swing.JLabel jLabelGordura1;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelLog;
    private javax.swing.JLabel jLabelMassa;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JTextField tfCpf;
    private javax.swing.JTextField tfData;
    private javax.swing.JTextField tfGordura;
    private javax.swing.JTextField tfHora;
    private javax.swing.JTextField tfMassa;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPeso;
    private javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
    private java.sql.Connection con;
    private java.sql.Statement stmt;
    private java.sql.Statement stmtNavegar;
    private java.sql.ResultSet rsNavegar;
    private dao.ClientesDao clientesDao;
    
    private void iniciarBD() {
        
        
        try {
            clientesDao = new ClientesDao();
        } catch ( Exception e ) {
            JOptionPane.showMessageDialog( this, "Erro: " + e.getMessage() );
        }
    }
   public void mostrarDados( Clientes clientes ) {
        tfCpf.setText( String.valueOf( clientes.getCpf() ) );
        tfNome.setText( String.valueOf( clientes.getNome() ) );
        tfTelefone.setText( String.valueOf( clientes.getTelefone() ) );
        tfData.setText( String.valueOf( clientes.getData() ) );
        tfHora.setText( String.valueOf( clientes.getHora() ) );
        tfPeso.setText( String.valueOf( clientes.getPeso() ) );
        tfGordura.setText( String.valueOf( clientes.getGordura() ) );
        tfMassa.setText( String.valueOf( clientes.getMassa() ) );
    }
    public void primeiro() {
        try {
                Clientes clientes = clientesDao.primeiro();

                if ( clientes != null) {
                    mostrarDados( clientes );
                }                    
            
        } catch ( SQLException e ) {
            JOptionPane.showMessageDialog( this, "Erro: " + e.getMessage() );
        }
    }
  
}

