/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.TreinosDao;
import entity.Treinos;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author WingedWarlock
 */
public class CadastrarTreinos extends javax.swing.JDialog {

    /**
     * Creates new form CadastrarTreinos
     */
    public CadastrarTreinos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.addComponentListener(new ComponentAdapter() {

public void componentMoved(ComponentEvent e) {

setEnabled(false);

setEnabled(true);

}

});
        iniciarBD();
        primeiro();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNome = new javax.swing.JTextField();
        jLabelCod = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabelGerenciarUsuarios = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        tfCod = new javax.swing.JTextField();
        tfCategoria = new javax.swing.JTextField();
        jLabelNome1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(tfNome);
        tfNome.setBounds(80, 70, 270, 27);

        jLabelCod.setText("Código");
        getContentPane().add(jLabelCod);
        jLabelCod.setBounds(40, 30, 100, 27);

        jLabelNome.setText("Nome");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(40, 70, 90, 27);

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Add.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setMaximumSize(new java.awt.Dimension(180, 70));
        jButtonLimpar.setMinimumSize(new java.awt.Dimension(180, 70));
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(10, 210, 120, 50);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/salvar.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setMaximumSize(new java.awt.Dimension(180, 70));
        jButtonSalvar.setMinimumSize(new java.awt.Dimension(180, 70));
        jButtonSalvar.setPreferredSize(new java.awt.Dimension(101, 49));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(140, 200, 130, 70);

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/excluir.jpg"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setMaximumSize(new java.awt.Dimension(180, 70));
        jButtonExcluir.setMinimumSize(new java.awt.Dimension(180, 70));
        jButtonExcluir.setPreferredSize(new java.awt.Dimension(180, 70));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(280, 210, 110, 50);

        jLabelGerenciarUsuarios.setText("Gerenciar Treinos");
        getContentPane().add(jLabelGerenciarUsuarios);
        jLabelGerenciarUsuarios.setBounds(140, 0, 130, 27);

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/find.jpg"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(20, 150, 140, 40);
        getContentPane().add(tfCod);
        tfCod.setBounds(80, 30, 270, 27);
        getContentPane().add(tfCategoria);
        tfCategoria.setBounds(100, 110, 250, 27);

        jLabelNome1.setText("Categoria");
        getContentPane().add(jLabelNome1);
        jLabelNome1.setBounds(40, 110, 90, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        tfCod.setText( "" );
        tfNome.setText( "" );
        tfCategoria.setText( "" );
        tfCod.requestFocus();  
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        try {
            int cod = Integer.parseInt( tfCod.getText() );  
            String nome = tfNome.getText(); 
            String categoria = tfCategoria.getText(); 
            Treinos treinos = new Treinos();
            treinos.setCod( cod );
            treinos.setNome( nome );
            treinos.setCategoria( categoria );
            treinosDao.salvarRegistro( treinos );
            JOptionPane.showMessageDialog( this, "Sucesso" );
                        
            } catch ( SQLException e1 ) {
               JOptionPane.showMessageDialog( this, "Erro: " + e1.getMessage() ); 
            }       
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        String cod = tfCod.getText();  
         
        try {
            treinosDao.excluirRegistro( Integer.parseInt( cod ) );
            JOptionPane.showMessageDialog( this, "Sucesso" );
        } catch ( SQLException e) {
            JOptionPane.showMessageDialog( this, "Erro: " + e.getMessage() );
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
         try {
                int cod = Integer.parseInt( JOptionPane.showInputDialog( this, "Digite o cod a pesquisar") );

                Treinos treinos = treinosDao.pesquisarTreinos( cod );

                if ( treinos != null ) {
                    mostrarDados( treinos );                    
                    JOptionPane.showMessageDialog( this, "Registro Encontrado." );
                } else {
                    JOptionPane.showMessageDialog( this, "Registro Não Encontrado ");
                }
        } catch ( SQLException e ) {
            JOptionPane.showMessageDialog( this, "Erro: " + e.getMessage() );
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarTreinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarTreinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarTreinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarTreinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            CadastrarTreinos dialog = new CadastrarTreinos(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
            }
        });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelGerenciarUsuarios;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNome1;
    private javax.swing.JTextField tfCategoria;
    private javax.swing.JTextField tfCod;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
    private java.sql.Connection con;
    private java.sql.Statement stmt;
    private java.sql.Statement stmtNavegar;
    private java.sql.ResultSet rsNavegar;
    private dao.TreinosDao treinosDao;
    
    private void iniciarBD() {
        
        
        try {
            treinosDao = new TreinosDao();
        } catch ( Exception e ) {
            JOptionPane.showMessageDialog( this, "Erro: " + e.getMessage() );
        }
    }
   public void mostrarDados( Treinos treinos ) {
        tfCod.setText( String.valueOf( treinos.getCod() ) );
        tfNome.setText( String.valueOf( treinos.getNome() ) );
        tfCategoria.setText( String.valueOf( treinos.getCategoria() ) );
    }
    public void primeiro() {
        try {
                Treinos treinos = treinosDao.primeiro();

                if ( treinos != null) {
                    mostrarDados( treinos );
                }                    
            
        } catch ( SQLException e ) {
            JOptionPane.showMessageDialog( this, "Erro: " + e.getMessage() );
        }
    }
  
}

