/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.FichasDao;
import dao.TreinosDao;
import entity.Fichas;
import entity.Treinos;
import java.awt.AWTException;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author WingedWarlock
 */
public class GerenciarFichas extends javax.swing.JDialog {

    /**
     * Creates new form CadastrarFichas
     */
    public GerenciarFichas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.addComponentListener(new ComponentAdapter() {

public void componentMoved(ComponentEvent e) {

setEnabled(false);

setEnabled(true);

}

});
        iniciarBD();
        montarListaTreinos();
        primeiro();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfR7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPeso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfGordura = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfMassa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfInstrutor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfData = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfT7 = new javax.swing.JComboBox<>();
        tfT1 = new javax.swing.JComboBox<>();
        tfT2 = new javax.swing.JComboBox<>();
        tfT3 = new javax.swing.JComboBox<>();
        tfT4 = new javax.swing.JComboBox<>();
        tfT5 = new javax.swing.JComboBox<>();
        tfT6 = new javax.swing.JComboBox<>();
        tfNome = new javax.swing.JTextField();
        tfS7 = new javax.swing.JTextField();
        tfR2 = new javax.swing.JTextField();
        tfR3 = new javax.swing.JTextField();
        tfR4 = new javax.swing.JTextField();
        tfR5 = new javax.swing.JTextField();
        tfR6 = new javax.swing.JTextField();
        tfR1 = new javax.swing.JTextField();
        tfS1 = new javax.swing.JTextField();
        tfS2 = new javax.swing.JTextField();
        tfS3 = new javax.swing.JTextField();
        tfS4 = new javax.swing.JTextField();
        tfS5 = new javax.swing.JTextField();
        tfS6 = new javax.swing.JTextField();
        tfR8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfT8 = new javax.swing.JComboBox<>();
        tfT9 = new javax.swing.JComboBox<>();
        tfT10 = new javax.swing.JComboBox<>();
        tfT11 = new javax.swing.JComboBox<>();
        tfT12 = new javax.swing.JComboBox<>();
        tfT13 = new javax.swing.JComboBox<>();
        tfT14 = new javax.swing.JComboBox<>();
        tfS8 = new javax.swing.JTextField();
        tfR9 = new javax.swing.JTextField();
        tfR10 = new javax.swing.JTextField();
        tfR11 = new javax.swing.JTextField();
        tfR12 = new javax.swing.JTextField();
        tfR13 = new javax.swing.JTextField();
        tfR14 = new javax.swing.JTextField();
        tfS9 = new javax.swing.JTextField();
        tfS10 = new javax.swing.JTextField();
        tfS11 = new javax.swing.JTextField();
        tfS12 = new javax.swing.JTextField();
        tfS13 = new javax.swing.JTextField();
        tfS14 = new javax.swing.JTextField();
        tfR15 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfT15 = new javax.swing.JComboBox<>();
        tfT16 = new javax.swing.JComboBox<>();
        tfT17 = new javax.swing.JComboBox<>();
        tfT18 = new javax.swing.JComboBox<>();
        tfT19 = new javax.swing.JComboBox<>();
        tfT20 = new javax.swing.JComboBox<>();
        tfT21 = new javax.swing.JComboBox<>();
        tfS15 = new javax.swing.JTextField();
        tfR16 = new javax.swing.JTextField();
        tfR17 = new javax.swing.JTextField();
        tfR18 = new javax.swing.JTextField();
        tfR19 = new javax.swing.JTextField();
        tfR20 = new javax.swing.JTextField();
        tfR21 = new javax.swing.JTextField();
        tfS16 = new javax.swing.JTextField();
        tfS17 = new javax.swing.JTextField();
        tfS18 = new javax.swing.JTextField();
        tfS19 = new javax.swing.JTextField();
        tfS20 = new javax.swing.JTextField();
        tfS21 = new javax.swing.JTextField();
        tfR28 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfT28 = new javax.swing.JComboBox<>();
        tfT22 = new javax.swing.JComboBox<>();
        tfT23 = new javax.swing.JComboBox<>();
        tfT24 = new javax.swing.JComboBox<>();
        tfT25 = new javax.swing.JComboBox<>();
        tfT26 = new javax.swing.JComboBox<>();
        tfT27 = new javax.swing.JComboBox<>();
        tfS28 = new javax.swing.JTextField();
        tfR23 = new javax.swing.JTextField();
        tfR24 = new javax.swing.JTextField();
        tfR25 = new javax.swing.JTextField();
        tfR26 = new javax.swing.JTextField();
        tfR27 = new javax.swing.JTextField();
        tfR22 = new javax.swing.JTextField();
        tfS22 = new javax.swing.JTextField();
        tfS23 = new javax.swing.JTextField();
        tfS24 = new javax.swing.JTextField();
        tfS25 = new javax.swing.JTextField();
        tfS26 = new javax.swing.JTextField();
        tfS27 = new javax.swing.JTextField();
        tfR29 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfT29 = new javax.swing.JComboBox<>();
        tfT30 = new javax.swing.JComboBox<>();
        tfT31 = new javax.swing.JComboBox<>();
        tfT32 = new javax.swing.JComboBox<>();
        tfT33 = new javax.swing.JComboBox<>();
        tfT34 = new javax.swing.JComboBox<>();
        tfT35 = new javax.swing.JComboBox<>();
        tfS29 = new javax.swing.JTextField();
        tfR30 = new javax.swing.JTextField();
        tfR31 = new javax.swing.JTextField();
        tfR32 = new javax.swing.JTextField();
        tfR33 = new javax.swing.JTextField();
        tfR34 = new javax.swing.JTextField();
        tfR35 = new javax.swing.JTextField();
        tfS30 = new javax.swing.JTextField();
        tfS31 = new javax.swing.JTextField();
        tfS32 = new javax.swing.JTextField();
        tfS33 = new javax.swing.JTextField();
        tfS34 = new javax.swing.JTextField();
        tfS35 = new javax.swing.JTextField();
        tfR36 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tfT36 = new javax.swing.JComboBox<>();
        tfT37 = new javax.swing.JComboBox<>();
        tfT38 = new javax.swing.JComboBox<>();
        tfT39 = new javax.swing.JComboBox<>();
        tfT40 = new javax.swing.JComboBox<>();
        tfT41 = new javax.swing.JComboBox<>();
        tfT42 = new javax.swing.JComboBox<>();
        tfS36 = new javax.swing.JTextField();
        tfR37 = new javax.swing.JTextField();
        tfR38 = new javax.swing.JTextField();
        tfR39 = new javax.swing.JTextField();
        tfR40 = new javax.swing.JTextField();
        tfR41 = new javax.swing.JTextField();
        tfR42 = new javax.swing.JTextField();
        tfS37 = new javax.swing.JTextField();
        tfS38 = new javax.swing.JTextField();
        tfS39 = new javax.swing.JTextField();
        tfS40 = new javax.swing.JTextField();
        tfS41 = new javax.swing.JTextField();
        tfS42 = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfCod = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1400, 725));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Aluno (cod)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 20, 70, 27);
        getContentPane().add(tfR7);
        tfR7.setBounds(370, 270, 50, 27);

        jLabel2.setText("Gordura");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(590, 20, 80, 27);
        getContentPane().add(tfPeso);
        tfPeso.setBounds(450, 20, 130, 27);

        jLabel3.setText("Peso");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 20, 80, 27);
        getContentPane().add(tfGordura);
        tfGordura.setBounds(640, 20, 80, 27);

        jLabel4.setText("Massa muscular");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(730, 20, 130, 27);
        getContentPane().add(tfMassa);
        tfMassa.setBounds(830, 20, 60, 27);

        jLabel5.setText("Instrutor");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(910, 20, 120, 27);
        getContentPane().add(tfInstrutor);
        tfInstrutor.setBounds(960, 20, 170, 27);

        jLabel6.setText("Data");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1140, 20, 120, 27);
        getContentPane().add(tfData);
        tfData.setBounds(1180, 20, 180, 27);

        jLabel10.setText("Segunda-Feira                                                                                     Repetições   Series");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 60, 510, 27);

        getContentPane().add(tfT7);
        tfT7.setBounds(30, 270, 330, 27);

        getContentPane().add(tfT1);
        tfT1.setBounds(30, 90, 330, 27);

        getContentPane().add(tfT2);
        tfT2.setBounds(30, 120, 330, 27);

        getContentPane().add(tfT3);
        tfT3.setBounds(30, 150, 330, 27);

        getContentPane().add(tfT4);
        tfT4.setBounds(30, 180, 330, 27);

        getContentPane().add(tfT5);
        tfT5.setBounds(30, 210, 330, 27);

        getContentPane().add(tfT6);
        tfT6.setBounds(30, 240, 330, 27);
        getContentPane().add(tfNome);
        tfNome.setBounds(270, 20, 130, 27);
        getContentPane().add(tfS7);
        tfS7.setBounds(430, 270, 40, 27);
        getContentPane().add(tfR2);
        tfR2.setBounds(370, 120, 50, 27);
        getContentPane().add(tfR3);
        tfR3.setBounds(370, 150, 50, 27);

        tfR4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfR4ActionPerformed(evt);
            }
        });
        getContentPane().add(tfR4);
        tfR4.setBounds(370, 180, 50, 27);
        getContentPane().add(tfR5);
        tfR5.setBounds(370, 210, 50, 27);
        getContentPane().add(tfR6);
        tfR6.setBounds(370, 240, 50, 27);

        tfR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfR1ActionPerformed(evt);
            }
        });
        getContentPane().add(tfR1);
        tfR1.setBounds(370, 90, 50, 27);
        getContentPane().add(tfS1);
        tfS1.setBounds(430, 90, 40, 27);
        getContentPane().add(tfS2);
        tfS2.setBounds(430, 120, 40, 27);
        getContentPane().add(tfS3);
        tfS3.setBounds(430, 150, 40, 27);
        getContentPane().add(tfS4);
        tfS4.setBounds(430, 180, 40, 27);
        getContentPane().add(tfS5);
        tfS5.setBounds(430, 210, 40, 27);
        getContentPane().add(tfS6);
        tfS6.setBounds(430, 240, 40, 27);
        getContentPane().add(tfR8);
        tfR8.setBounds(820, 90, 50, 27);

        jLabel12.setText("Terça-Feira                                                                                          Repetições   Series");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(480, 60, 510, 27);

        getContentPane().add(tfT8);
        tfT8.setBounds(480, 90, 330, 27);

        getContentPane().add(tfT9);
        tfT9.setBounds(480, 120, 330, 27);

        getContentPane().add(tfT10);
        tfT10.setBounds(480, 150, 330, 27);

        getContentPane().add(tfT11);
        tfT11.setBounds(480, 180, 330, 27);

        getContentPane().add(tfT12);
        tfT12.setBounds(480, 210, 330, 27);

        getContentPane().add(tfT13);
        tfT13.setBounds(480, 240, 330, 27);

        getContentPane().add(tfT14);
        tfT14.setBounds(480, 270, 330, 27);
        getContentPane().add(tfS8);
        tfS8.setBounds(880, 90, 40, 27);
        getContentPane().add(tfR9);
        tfR9.setBounds(820, 120, 50, 27);
        getContentPane().add(tfR10);
        tfR10.setBounds(820, 150, 50, 27);
        getContentPane().add(tfR11);
        tfR11.setBounds(820, 180, 50, 27);
        getContentPane().add(tfR12);
        tfR12.setBounds(820, 210, 50, 27);
        getContentPane().add(tfR13);
        tfR13.setBounds(820, 240, 50, 27);
        getContentPane().add(tfR14);
        tfR14.setBounds(820, 270, 50, 27);
        getContentPane().add(tfS9);
        tfS9.setBounds(880, 120, 40, 27);
        getContentPane().add(tfS10);
        tfS10.setBounds(880, 150, 40, 27);
        getContentPane().add(tfS11);
        tfS11.setBounds(880, 180, 40, 27);
        getContentPane().add(tfS12);
        tfS12.setBounds(880, 210, 40, 27);
        getContentPane().add(tfS13);
        tfS13.setBounds(880, 240, 40, 27);
        getContentPane().add(tfS14);
        tfS14.setBounds(880, 270, 40, 27);
        getContentPane().add(tfR15);
        tfR15.setBounds(1260, 90, 50, 27);

        jLabel13.setText("Quarta-Feira                                                                                    Repetições   Series");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(930, 60, 510, 27);

        getContentPane().add(tfT15);
        tfT15.setBounds(930, 90, 320, 27);

        getContentPane().add(tfT16);
        tfT16.setBounds(930, 120, 320, 27);

        getContentPane().add(tfT17);
        tfT17.setBounds(930, 150, 320, 27);

        getContentPane().add(tfT18);
        tfT18.setBounds(930, 180, 320, 27);

        getContentPane().add(tfT19);
        tfT19.setBounds(930, 210, 320, 27);

        getContentPane().add(tfT20);
        tfT20.setBounds(930, 240, 320, 27);

        getContentPane().add(tfT21);
        tfT21.setBounds(930, 270, 320, 27);
        getContentPane().add(tfS15);
        tfS15.setBounds(1320, 90, 40, 27);
        getContentPane().add(tfR16);
        tfR16.setBounds(1260, 120, 50, 27);
        getContentPane().add(tfR17);
        tfR17.setBounds(1260, 150, 50, 27);
        getContentPane().add(tfR18);
        tfR18.setBounds(1260, 180, 50, 27);
        getContentPane().add(tfR19);
        tfR19.setBounds(1260, 210, 50, 27);
        getContentPane().add(tfR20);
        tfR20.setBounds(1260, 240, 50, 27);
        getContentPane().add(tfR21);
        tfR21.setBounds(1260, 270, 50, 27);
        getContentPane().add(tfS16);
        tfS16.setBounds(1320, 120, 40, 27);
        getContentPane().add(tfS17);
        tfS17.setBounds(1320, 150, 40, 27);
        getContentPane().add(tfS18);
        tfS18.setBounds(1320, 180, 40, 27);
        getContentPane().add(tfS19);
        tfS19.setBounds(1320, 210, 40, 27);
        getContentPane().add(tfS20);
        tfS20.setBounds(1320, 240, 40, 27);
        getContentPane().add(tfS21);
        tfS21.setBounds(1320, 270, 40, 27);
        getContentPane().add(tfR28);
        tfR28.setBounds(370, 520, 50, 27);

        jLabel11.setText("Quinta-Feira                                                                                        Repetições   Series");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 310, 510, 27);

        getContentPane().add(tfT28);
        tfT28.setBounds(30, 520, 330, 27);

        getContentPane().add(tfT22);
        tfT22.setBounds(30, 340, 330, 27);

        getContentPane().add(tfT23);
        tfT23.setBounds(30, 370, 330, 27);

        getContentPane().add(tfT24);
        tfT24.setBounds(30, 400, 330, 27);

        getContentPane().add(tfT25);
        tfT25.setBounds(30, 430, 330, 27);

        getContentPane().add(tfT26);
        tfT26.setBounds(30, 460, 330, 27);

        getContentPane().add(tfT27);
        tfT27.setBounds(30, 490, 330, 27);
        getContentPane().add(tfS28);
        tfS28.setBounds(430, 520, 40, 27);
        getContentPane().add(tfR23);
        tfR23.setBounds(370, 370, 50, 27);
        getContentPane().add(tfR24);
        tfR24.setBounds(370, 400, 50, 27);
        getContentPane().add(tfR25);
        tfR25.setBounds(370, 430, 50, 27);
        getContentPane().add(tfR26);
        tfR26.setBounds(370, 460, 50, 27);
        getContentPane().add(tfR27);
        tfR27.setBounds(370, 490, 50, 27);
        getContentPane().add(tfR22);
        tfR22.setBounds(370, 340, 50, 27);
        getContentPane().add(tfS22);
        tfS22.setBounds(430, 340, 40, 27);
        getContentPane().add(tfS23);
        tfS23.setBounds(430, 370, 40, 27);
        getContentPane().add(tfS24);
        tfS24.setBounds(430, 400, 40, 27);
        getContentPane().add(tfS25);
        tfS25.setBounds(430, 430, 40, 27);
        getContentPane().add(tfS26);
        tfS26.setBounds(430, 460, 40, 27);
        getContentPane().add(tfS27);
        tfS27.setBounds(430, 490, 40, 27);
        getContentPane().add(tfR29);
        tfR29.setBounds(820, 340, 50, 27);

        jLabel23.setText("Sexta-Feira                                                                                            Repetições   Series");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(480, 310, 510, 27);

        getContentPane().add(tfT29);
        tfT29.setBounds(480, 340, 330, 27);

        getContentPane().add(tfT30);
        tfT30.setBounds(480, 370, 330, 27);

        getContentPane().add(tfT31);
        tfT31.setBounds(480, 400, 330, 27);

        getContentPane().add(tfT32);
        tfT32.setBounds(480, 430, 330, 27);

        getContentPane().add(tfT33);
        tfT33.setBounds(480, 460, 330, 27);

        getContentPane().add(tfT34);
        tfT34.setBounds(480, 490, 330, 27);

        getContentPane().add(tfT35);
        tfT35.setBounds(480, 520, 330, 27);
        getContentPane().add(tfS29);
        tfS29.setBounds(880, 340, 40, 27);
        getContentPane().add(tfR30);
        tfR30.setBounds(820, 370, 50, 27);
        getContentPane().add(tfR31);
        tfR31.setBounds(820, 400, 50, 27);
        getContentPane().add(tfR32);
        tfR32.setBounds(820, 430, 50, 27);
        getContentPane().add(tfR33);
        tfR33.setBounds(820, 460, 50, 27);
        getContentPane().add(tfR34);
        tfR34.setBounds(820, 490, 50, 27);
        getContentPane().add(tfR35);
        tfR35.setBounds(820, 520, 50, 27);
        getContentPane().add(tfS30);
        tfS30.setBounds(880, 370, 40, 27);
        getContentPane().add(tfS31);
        tfS31.setBounds(880, 400, 40, 27);
        getContentPane().add(tfS32);
        tfS32.setBounds(880, 430, 40, 27);
        getContentPane().add(tfS33);
        tfS33.setBounds(880, 460, 40, 27);
        getContentPane().add(tfS34);
        tfS34.setBounds(880, 490, 40, 27);
        getContentPane().add(tfS35);
        tfS35.setBounds(880, 520, 40, 27);
        getContentPane().add(tfR36);
        tfR36.setBounds(1260, 340, 50, 27);

        jLabel24.setText("Sábado                                                                                             Repetições   Series");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(930, 310, 510, 27);

        getContentPane().add(tfT36);
        tfT36.setBounds(930, 340, 320, 27);

        getContentPane().add(tfT37);
        tfT37.setBounds(930, 370, 320, 27);

        getContentPane().add(tfT38);
        tfT38.setBounds(930, 400, 320, 27);

        getContentPane().add(tfT39);
        tfT39.setBounds(930, 430, 320, 27);

        getContentPane().add(tfT40);
        tfT40.setBounds(930, 460, 320, 27);

        getContentPane().add(tfT41);
        tfT41.setBounds(930, 490, 320, 27);

        getContentPane().add(tfT42);
        tfT42.setBounds(930, 520, 320, 27);
        getContentPane().add(tfS36);
        tfS36.setBounds(1320, 340, 40, 27);
        getContentPane().add(tfR37);
        tfR37.setBounds(1260, 370, 50, 27);
        getContentPane().add(tfR38);
        tfR38.setBounds(1260, 400, 50, 27);
        getContentPane().add(tfR39);
        tfR39.setBounds(1260, 430, 50, 27);
        getContentPane().add(tfR40);
        tfR40.setBounds(1260, 460, 50, 27);
        getContentPane().add(tfR41);
        tfR41.setBounds(1260, 490, 50, 27);
        getContentPane().add(tfR42);
        tfR42.setBounds(1260, 520, 50, 27);
        getContentPane().add(tfS37);
        tfS37.setBounds(1320, 370, 40, 27);
        getContentPane().add(tfS38);
        tfS38.setBounds(1320, 400, 40, 27);
        getContentPane().add(tfS39);
        tfS39.setBounds(1320, 430, 40, 27);
        getContentPane().add(tfS40);
        tfS40.setBounds(1320, 460, 40, 27);
        getContentPane().add(tfS41);
        tfS41.setBounds(1320, 490, 40, 27);
        getContentPane().add(tfS42);
        tfS42.setBounds(1320, 520, 40, 27);

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/find.jpg"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(40, 620, 140, 40);

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Add.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(300, 620, 120, 50);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/salvar.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(650, 610, 130, 70);

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/excluir.jpg"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(1000, 620, 110, 50);

        jLabel7.setText("Código");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 20, 70, 27);
        getContentPane().add(tfCod);
        tfCod.setBounds(70, 20, 120, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        
        tfCod.setText( "" );
        tfNome.setText( "" );
        tfPeso.setText( "" );
        tfGordura.setText( "" );
        tfMassa.setText( "" );
        tfInstrutor.setText( "" );
        tfData.setText( "" );
        tfT1.setSelectedIndex( 0 );
        tfT2.setSelectedIndex( 0 );
        tfT3.setSelectedIndex( 0 );
        tfT4.setSelectedIndex( 0 );
        tfT5.setSelectedIndex( 0 );
        tfT6.setSelectedIndex( 0 );
        tfT7.setSelectedIndex( 0 );
        tfT8.setSelectedIndex( 0 );
        tfT9.setSelectedIndex( 0 );
        tfT10.setSelectedIndex( 0 );
        tfT11.setSelectedIndex( 0 );
        tfT12.setSelectedIndex( 0 );
        tfT13.setSelectedIndex( 0 );
        tfT14.setSelectedIndex( 0 );
        tfT15.setSelectedIndex( 0 );
        tfT16.setSelectedIndex( 0 );
        tfT17.setSelectedIndex( 0 );
        tfT18.setSelectedIndex( 0 );
        tfT19.setSelectedIndex( 0 );
        tfT20.setSelectedIndex( 0 );
        tfT21.setSelectedIndex( 0 );
        tfT22.setSelectedIndex( 0 );
        tfT23.setSelectedIndex( 0 );
        tfT24.setSelectedIndex( 0 );
        tfT25.setSelectedIndex( 0 );
        tfT26.setSelectedIndex( 0 );
        tfT27.setSelectedIndex( 0 );
        tfT28.setSelectedIndex( 0 );
        tfT29.setSelectedIndex( 0 );
        tfT30.setSelectedIndex( 0 );
        tfT31.setSelectedIndex( 0 );
        tfT32.setSelectedIndex( 0 );
        tfT33.setSelectedIndex( 0 );
        tfT34.setSelectedIndex( 0 );
        tfT35.setSelectedIndex( 0 );
        tfT36.setSelectedIndex( 0 );
        tfT37.setSelectedIndex( 0 );
        tfT38.setSelectedIndex( 0 );
        tfT39.setSelectedIndex( 0 );
        tfT40.setSelectedIndex( 0 );
        tfT41.setSelectedIndex( 0 );
        tfT42.setSelectedIndex( 0 );
        tfS1.setText( "" );
        tfS2.setText( "" );
        tfS3.setText( "" );
        tfS4.setText( "" );
        tfS5.setText( "" );
        tfS6.setText( "" );
        tfS7.setText( "" );
        tfS8.setText( "" );
        tfS9.setText( "" );
        tfS10.setText( "" );
        tfS11.setText( "" );
        tfS12.setText( "" );
        tfS13.setText( "" );
        tfS14.setText( "" );
        tfS15.setText( "" );
        tfS16.setText( "" );
        tfS17.setText( "" );
        tfS18.setText( "" );
        tfS19.setText( "" );
        tfS20.setText( "" );
        tfS21.setText( "" );
        tfS22.setText( "" );
        tfS23.setText( "" );
        tfS24.setText( "" );
        tfS25.setText( "" );
        tfS26.setText( "" );
        tfS27.setText( "" );
        tfS28.setText( "" );
        tfS29.setText( "" );
        tfS30.setText( "" );
        tfS31.setText( "" );
        tfS32.setText( "" );
        tfS33.setText( "" );
        tfS34.setText( "" );
        tfS35.setText( "" );
        tfS36.setText( "" );
        tfS37.setText( "" );
        tfS38.setText( "" );
        tfS39.setText( "" );
        tfS40.setText( "" );
        tfS41.setText( "" );
        tfS42.setText( "" );
        tfR1.setText( "" );
        tfR2.setText( "" );
        tfR3.setText( "" );
        tfR4.setText( "" );
        tfR5.setText( "" );
        tfR6.setText( "" );
        tfR7.setText( "" );
        tfR8.setText( "" );
        tfR9.setText( "" );
        tfR10.setText( "" );
        tfR11.setText( "" );
        tfR12.setText( "" );
        tfR13.setText( "" );
        tfR14.setText( "" );
        tfR15.setText( "" );
        tfR16.setText( "" );
        tfR17.setText( "" );
        tfR18.setText( "" );
        tfR19.setText( "" );
        tfR20.setText( "" );
        tfR21.setText( "" );
        tfR22.setText( "" );
        tfR23.setText( "" );
        tfR24.setText( "" );
        tfR25.setText( "" );
        tfR26.setText( "" );
        tfR27.setText( "" );
        tfR28.setText( "" );
        tfR29.setText( "" );
        tfR30.setText( "" );
        tfR31.setText( "" );
        tfR32.setText( "" );
        tfR33.setText( "" );
        tfR34.setText( "" );
        tfR35.setText( "" );
        tfR36.setText( "" );
        tfR37.setText( "" );
        tfR38.setText( "" );
        tfR39.setText( "" );
        tfR40.setText( "" );
        tfR41.setText( "" );
        tfR42.setText( "" );
        tfCod.requestFocus();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        try {
                int cod = Integer.parseInt( JOptionPane.showInputDialog( this, "Digite o codigo a pesquisar") );

                Fichas fichas = fichasDao.pesquisarFichas( cod );

                if ( fichas != null ) {
                    mostrarDados( fichas );                    
                    JOptionPane.showMessageDialog( this, "Registro Encontrado." );
                } else {
                    JOptionPane.showMessageDialog( this, "Registro Não Encontrado ");
                }
        } catch ( SQLException e ) {
            JOptionPane.showMessageDialog( this, "Erro: " + e.getMessage() );
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        String cod = tfCod.getText();  
         
        try {
            fichasDao.excluirRegistro( Integer.parseInt( cod ) );
            JOptionPane.showMessageDialog( this, "Sucesso" );
        } catch ( SQLException e) {
            JOptionPane.showMessageDialog( this, "Erro: " + e.getMessage() );
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        try {
            int cod = Integer.parseInt( tfCod.getText() );  
            int nome = Integer.parseInt(tfNome.getText()); 
            float peso = Float.parseFloat(tfPeso.getText()); 
            float gordura = Float.parseFloat(tfGordura.getText()); 
            float massa = Float.parseFloat(tfMassa.getText()); 
            int instrutor = Integer.parseInt(tfInstrutor.getText()); 
            String data = tfData.getText(); 
  
            int t1 = treinosDao.getCodTreinosByNome(tfT1.getSelectedItem().toString() );
            int t2 = treinosDao.getCodTreinosByNome(tfT2.getSelectedItem().toString() );
            int t3 = treinosDao.getCodTreinosByNome(tfT3.getSelectedItem().toString() );
            int t4 = treinosDao.getCodTreinosByNome(tfT4.getSelectedItem().toString() );
            int t5 = treinosDao.getCodTreinosByNome(tfT5.getSelectedItem().toString() );
            int t6 = treinosDao.getCodTreinosByNome(tfT6.getSelectedItem().toString() );
            int t7 = treinosDao.getCodTreinosByNome(tfT7.getSelectedItem().toString() );
            int t8 = treinosDao.getCodTreinosByNome(tfT8.getSelectedItem().toString() );
            int t9 = treinosDao.getCodTreinosByNome(tfT9.getSelectedItem().toString() );
            int t10 = treinosDao.getCodTreinosByNome(tfT10.getSelectedItem().toString() );
            int t11 = treinosDao.getCodTreinosByNome(tfT11.getSelectedItem().toString() );
            int t12 = treinosDao.getCodTreinosByNome(tfT12.getSelectedItem().toString() );
            int t13 = treinosDao.getCodTreinosByNome(tfT13.getSelectedItem().toString() );
            int t14 = treinosDao.getCodTreinosByNome(tfT14.getSelectedItem().toString() );
            int t15 = treinosDao.getCodTreinosByNome(tfT15.getSelectedItem().toString() );
            int t16 = treinosDao.getCodTreinosByNome(tfT16.getSelectedItem().toString() );
            int t17 = treinosDao.getCodTreinosByNome(tfT17.getSelectedItem().toString() );
            int t18 = treinosDao.getCodTreinosByNome(tfT18.getSelectedItem().toString() );
            int t19 = treinosDao.getCodTreinosByNome(tfT19.getSelectedItem().toString() );
            int t20 = treinosDao.getCodTreinosByNome(tfT20.getSelectedItem().toString() );
            int t21 = treinosDao.getCodTreinosByNome(tfT21.getSelectedItem().toString() );
            int t22 = treinosDao.getCodTreinosByNome(tfT22.getSelectedItem().toString() );
            int t23 = treinosDao.getCodTreinosByNome(tfT23.getSelectedItem().toString() );
            int t24 = treinosDao.getCodTreinosByNome(tfT24.getSelectedItem().toString() );
            int t25 = treinosDao.getCodTreinosByNome(tfT25.getSelectedItem().toString() );
            int t26 = treinosDao.getCodTreinosByNome(tfT26.getSelectedItem().toString() );
            int t27 = treinosDao.getCodTreinosByNome(tfT27.getSelectedItem().toString() );
            int t28 = treinosDao.getCodTreinosByNome(tfT28.getSelectedItem().toString() );
            int t29 = treinosDao.getCodTreinosByNome(tfT29.getSelectedItem().toString() );
            int t30 = treinosDao.getCodTreinosByNome(tfT30.getSelectedItem().toString() );
            int t31 = treinosDao.getCodTreinosByNome(tfT31.getSelectedItem().toString() );
            int t32 = treinosDao.getCodTreinosByNome(tfT32.getSelectedItem().toString() );
            int t33 = treinosDao.getCodTreinosByNome(tfT33.getSelectedItem().toString() );
            int t34 = treinosDao.getCodTreinosByNome(tfT34.getSelectedItem().toString() );
            int t35 = treinosDao.getCodTreinosByNome(tfT35.getSelectedItem().toString() );
            int t36 = treinosDao.getCodTreinosByNome(tfT36.getSelectedItem().toString() );
            int t37 = treinosDao.getCodTreinosByNome(tfT37.getSelectedItem().toString() );
            int t38 = treinosDao.getCodTreinosByNome(tfT38.getSelectedItem().toString() );
            int t39 = treinosDao.getCodTreinosByNome(tfT39.getSelectedItem().toString() );
            int t40 = treinosDao.getCodTreinosByNome(tfT40.getSelectedItem().toString() );
            int t41 = treinosDao.getCodTreinosByNome(tfT41.getSelectedItem().toString() );
            int t42 = treinosDao.getCodTreinosByNome(tfT42.getSelectedItem().toString() );
            int r1 = Integer.parseInt(tfR1.getText());
            int r2 = Integer.parseInt(tfR2.getText());
            int r3 = Integer.parseInt(tfR3.getText());
            int r4 = Integer.parseInt(tfR4.getText());
            int r5 = Integer.parseInt(tfR5.getText());
            int r6 = Integer.parseInt(tfR6.getText());
            int r7 = Integer.parseInt(tfR7.getText());
            int r8 = Integer.parseInt(tfR8.getText());
            int r9 = Integer.parseInt(tfR9.getText());
            int r10 = Integer.parseInt(tfR10.getText());
            int r11 = Integer.parseInt(tfR11.getText());
            int r12 = Integer.parseInt(tfR12.getText());
            int r13 = Integer.parseInt(tfR13.getText());
            int r14 = Integer.parseInt(tfR14.getText());
            int r15 = Integer.parseInt(tfR15.getText());
            int r16 = Integer.parseInt(tfR16.getText());
            int r17 = Integer.parseInt(tfR17.getText());
            int r18 = Integer.parseInt(tfR18.getText());
            int r19 = Integer.parseInt(tfR19.getText());
            int r20 = Integer.parseInt(tfR20.getText());
            int r21 = Integer.parseInt(tfR21.getText());
            int r22 = Integer.parseInt(tfR22.getText());
            int r23 = Integer.parseInt(tfR23.getText());
            int r24 = Integer.parseInt(tfR24.getText());
            int r25 = Integer.parseInt(tfR25.getText());
            int r26 = Integer.parseInt(tfR26.getText());
            int r27 = Integer.parseInt(tfR27.getText());
            int r28 = Integer.parseInt(tfR28.getText());
            int r29 = Integer.parseInt(tfR29.getText());
            int r30 = Integer.parseInt(tfR30.getText());
            int r31 = Integer.parseInt(tfR31.getText());
            int r32 = Integer.parseInt(tfR32.getText());
            int r33 = Integer.parseInt(tfR33.getText());
            int r34 = Integer.parseInt(tfR34.getText());
            int r35 = Integer.parseInt(tfR35.getText());
            int r36 = Integer.parseInt(tfR36.getText());
            int r37 = Integer.parseInt(tfR37.getText());
            int r38 = Integer.parseInt(tfR38.getText());
            int r39 = Integer.parseInt(tfR39.getText());
            int r40 = Integer.parseInt(tfR40.getText());
            int r41 = Integer.parseInt(tfR41.getText());
            int r42 = Integer.parseInt(tfR42.getText());
            int s1 = Integer.parseInt(tfS1.getText());
            int s2 = Integer.parseInt(tfS2.getText());
            int s3 = Integer.parseInt(tfS3.getText());
            int s4 = Integer.parseInt(tfS4.getText());
            int s5 = Integer.parseInt(tfS5.getText());
            int s6 = Integer.parseInt(tfS6.getText());
            int s7 = Integer.parseInt(tfS7.getText());
            int s8 = Integer.parseInt(tfS8.getText());
            int s9 = Integer.parseInt(tfS9.getText());
            int s10 = Integer.parseInt(tfS10.getText());
            int s11 = Integer.parseInt(tfS11.getText());
            int s12 = Integer.parseInt(tfS12.getText());
            int s13 = Integer.parseInt(tfS13.getText());
            int s14 = Integer.parseInt(tfS14.getText());
            int s15 = Integer.parseInt(tfS15.getText());
            int s16 = Integer.parseInt(tfS16.getText());
            int s17 = Integer.parseInt(tfS17.getText());
            int s18 = Integer.parseInt(tfS18.getText());
            int s19 = Integer.parseInt(tfS19.getText());
            int s20 = Integer.parseInt(tfS20.getText());
            int s21 = Integer.parseInt(tfS21.getText());
            int s22 = Integer.parseInt(tfS22.getText());
            int s23 = Integer.parseInt(tfS23.getText());
            int s24 = Integer.parseInt(tfS24.getText());
            int s25 = Integer.parseInt(tfS25.getText());
            int s26 = Integer.parseInt(tfS26.getText());
            int s27 = Integer.parseInt(tfS27.getText());
            int s28 = Integer.parseInt(tfS28.getText());
            int s29 = Integer.parseInt(tfS29.getText());
            int s30 = Integer.parseInt(tfS30.getText());
            int s31 = Integer.parseInt(tfS31.getText());
            int s32 = Integer.parseInt(tfS32.getText());
            int s33 = Integer.parseInt(tfS33.getText());
            int s34 = Integer.parseInt(tfS34.getText());
            int s35 = Integer.parseInt(tfS35.getText());
            int s36 = Integer.parseInt(tfS36.getText());
            int s37 = Integer.parseInt(tfS37.getText());
            int s38 = Integer.parseInt(tfS38.getText());
            int s39 = Integer.parseInt(tfS39.getText());
            int s40 = Integer.parseInt(tfS40.getText());
            int s41 = Integer.parseInt(tfS41.getText());
            int s42 = Integer.parseInt(tfS42.getText());
            
            Fichas fichas = new Fichas();
            fichas.setCod( cod );
            fichas.setNome( nome );
            fichas.setPeso( peso );
            fichas.setGordura( gordura );
            fichas.setMassa( massa );
            fichas.setInstrutor( instrutor );
            fichas.setData( data );
            fichas.setT1( t1 );
            fichas.setT2( t2 );
            fichas.setT3( t3 );
            fichas.setT4( t4 );
            fichas.setT5( t5 );
            fichas.setT6( t6 );
            fichas.setT7( t7 );
            fichas.setT8( t8 );
            fichas.setT9( t9 );
            fichas.setT10( t10 );
            fichas.setT11( t11 );
            fichas.setT12( t12 );
            fichas.setT13( t13 );
            fichas.setT14( t14 );
            fichas.setT15( t15 );
            fichas.setT16( t16 );
            fichas.setT17( t17 );
            fichas.setT18( t18 );
            fichas.setT19( t19 );
            fichas.setT20( t20 );
            fichas.setT21( t21 );
            fichas.setT22( t22 );
            fichas.setT23( t23 );
            fichas.setT24( t24 );
            fichas.setT25( t25 );
            fichas.setT26( t26 );
            fichas.setT27( t27 );
            fichas.setT28( t28 );
            fichas.setT29( t29 );
            fichas.setT30( t30 );
            fichas.setT31( t31 );
            fichas.setT32( t32 );
            fichas.setT33( t33 );
            fichas.setT34( t34 );
            fichas.setT35( t35 );
            fichas.setT36( t36 );
            fichas.setT37( t37 );
            fichas.setT38( t38 );
            fichas.setT39( t39 );
            fichas.setT40( t40 );
            fichas.setT41( t41 );
            fichas.setT42( t42 );
            fichas.setR1( r1 );
            fichas.setR2( r2 );
            fichas.setR3( r3 );
            fichas.setR4( r4 );
            fichas.setR5( r5 );
            fichas.setR6( r6 );
            fichas.setR7( r7 );
            fichas.setR8( r8 );
            fichas.setR9( r9 );
            fichas.setR10( r10 );
            fichas.setR11( r11 );
            fichas.setR12( r12 );
            fichas.setR13( r13 );
            fichas.setR14( r14 );
            fichas.setR15( r15 );
            fichas.setR16( r16 );
            fichas.setR17( r17 );
            fichas.setR18( r18 );
            fichas.setR19( r19 );
            fichas.setR20( r20 );
            fichas.setR21( r21 );
            fichas.setR22( r22 );
            fichas.setR23( r23 );
            fichas.setR24( r24 );
            fichas.setR25( r25 );
            fichas.setR26( r26 );
            fichas.setR27( r27 );
            fichas.setR28( r28 );
            fichas.setR29( r29 );
            fichas.setR30( r30 );
            fichas.setR31( r31 );
            fichas.setR32( r32 );
            fichas.setR33( r33 );
            fichas.setR34( r34 );
            fichas.setR35( r35 );
            fichas.setR36( r36 );
            fichas.setR37( r37 );
            fichas.setR38( r38 );
            fichas.setR39( r39 );
            fichas.setR40( r40 );
            fichas.setR41( r41 );
            fichas.setR42( r42 );
            fichas.setS1( s1 );
            fichas.setS2( s2 );
            fichas.setS3( s3 );
            fichas.setS4( s4 );
            fichas.setS5( s5 );
            fichas.setS6( s6 );
            fichas.setS7( s7 );
            fichas.setS8( s8 );
            fichas.setS9( s9 );
            fichas.setS10( s10 );
            fichas.setS11( s11 );
            fichas.setS12( s12 );
            fichas.setS13( s13 );
            fichas.setS14( s14 );
            fichas.setS15( s15 );
            fichas.setS16( s16 );
            fichas.setS17( s17 );
            fichas.setS18( s18 );
            fichas.setS19( s19 );
            fichas.setS20( s20 );
            fichas.setS21( s21 );
            fichas.setS22( s22 );
            fichas.setS23( s23 );
            fichas.setS24( s24 );
            fichas.setS25( s25 );
            fichas.setS26( s26 );
            fichas.setS27( s27 );
            fichas.setS28( s28 );
            fichas.setS29( s29 );
            fichas.setS30( s30 );
            fichas.setS31( s31 );
            fichas.setS32( s32 );
            fichas.setS33( s33 );
            fichas.setS34( s34 );
            fichas.setS35( s35 );
            fichas.setS36( s36 );
            fichas.setS37( s37 );
            fichas.setS38( s38 );
            fichas.setS39( s39 );
            fichas.setS40( s40 );
            fichas.setS41( s41 );
            fichas.setS42( s42 );

            fichasDao.salvarRegistro( fichas );
            Date data1 = new Date(System.currentTimeMillis());
            Robot robot = new Robot();
            BufferedImage bi = robot.createScreenCapture(new Rectangle(0,0,1375,600));
            ImageIO.write(bi,"jpg", new File("C://Users//WingedWarlock//Documents//NetBeansProjects//Academia2//src//FichasImagens//"+cod+"Ficha"+data1+".jpg"));
            JOptionPane.showMessageDialog( this, "Sucesso" );
                        
            } catch ( SQLException e1 ) {
               JOptionPane.showMessageDialog( this, "Erro: " + e1.getMessage() ); 
            } catch (AWTException ex) {      
            Logger.getLogger(GerenciarFichas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GerenciarFichas.class.getName()).log(Level.SEVERE, null, ex);
        }      
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void tfR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfR1ActionPerformed

    private void tfR4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfR4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfR4ActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarFichas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarFichas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarFichas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarFichas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            GerenciarFichas dialog = new GerenciarFichas(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
            }
        });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfCod;
    private javax.swing.JTextField tfData;
    private javax.swing.JTextField tfGordura;
    private javax.swing.JTextField tfInstrutor;
    private javax.swing.JTextField tfMassa;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPeso;
    private javax.swing.JTextField tfR1;
    private javax.swing.JTextField tfR10;
    private javax.swing.JTextField tfR11;
    private javax.swing.JTextField tfR12;
    private javax.swing.JTextField tfR13;
    private javax.swing.JTextField tfR14;
    private javax.swing.JTextField tfR15;
    private javax.swing.JTextField tfR16;
    private javax.swing.JTextField tfR17;
    private javax.swing.JTextField tfR18;
    private javax.swing.JTextField tfR19;
    private javax.swing.JTextField tfR2;
    private javax.swing.JTextField tfR20;
    private javax.swing.JTextField tfR21;
    private javax.swing.JTextField tfR22;
    private javax.swing.JTextField tfR23;
    private javax.swing.JTextField tfR24;
    private javax.swing.JTextField tfR25;
    private javax.swing.JTextField tfR26;
    private javax.swing.JTextField tfR27;
    private javax.swing.JTextField tfR28;
    private javax.swing.JTextField tfR29;
    private javax.swing.JTextField tfR3;
    private javax.swing.JTextField tfR30;
    private javax.swing.JTextField tfR31;
    private javax.swing.JTextField tfR32;
    private javax.swing.JTextField tfR33;
    private javax.swing.JTextField tfR34;
    private javax.swing.JTextField tfR35;
    private javax.swing.JTextField tfR36;
    private javax.swing.JTextField tfR37;
    private javax.swing.JTextField tfR38;
    private javax.swing.JTextField tfR39;
    private javax.swing.JTextField tfR4;
    private javax.swing.JTextField tfR40;
    private javax.swing.JTextField tfR41;
    private javax.swing.JTextField tfR42;
    private javax.swing.JTextField tfR5;
    private javax.swing.JTextField tfR6;
    private javax.swing.JTextField tfR7;
    private javax.swing.JTextField tfR8;
    private javax.swing.JTextField tfR9;
    private javax.swing.JTextField tfS1;
    private javax.swing.JTextField tfS10;
    private javax.swing.JTextField tfS11;
    private javax.swing.JTextField tfS12;
    private javax.swing.JTextField tfS13;
    private javax.swing.JTextField tfS14;
    private javax.swing.JTextField tfS15;
    private javax.swing.JTextField tfS16;
    private javax.swing.JTextField tfS17;
    private javax.swing.JTextField tfS18;
    private javax.swing.JTextField tfS19;
    private javax.swing.JTextField tfS2;
    private javax.swing.JTextField tfS20;
    private javax.swing.JTextField tfS21;
    private javax.swing.JTextField tfS22;
    private javax.swing.JTextField tfS23;
    private javax.swing.JTextField tfS24;
    private javax.swing.JTextField tfS25;
    private javax.swing.JTextField tfS26;
    private javax.swing.JTextField tfS27;
    private javax.swing.JTextField tfS28;
    private javax.swing.JTextField tfS29;
    private javax.swing.JTextField tfS3;
    private javax.swing.JTextField tfS30;
    private javax.swing.JTextField tfS31;
    private javax.swing.JTextField tfS32;
    private javax.swing.JTextField tfS33;
    private javax.swing.JTextField tfS34;
    private javax.swing.JTextField tfS35;
    private javax.swing.JTextField tfS36;
    private javax.swing.JTextField tfS37;
    private javax.swing.JTextField tfS38;
    private javax.swing.JTextField tfS39;
    private javax.swing.JTextField tfS4;
    private javax.swing.JTextField tfS40;
    private javax.swing.JTextField tfS41;
    private javax.swing.JTextField tfS42;
    private javax.swing.JTextField tfS5;
    private javax.swing.JTextField tfS6;
    private javax.swing.JTextField tfS7;
    private javax.swing.JTextField tfS8;
    private javax.swing.JTextField tfS9;
    private javax.swing.JComboBox<String> tfT1;
    private javax.swing.JComboBox<String> tfT10;
    private javax.swing.JComboBox<String> tfT11;
    private javax.swing.JComboBox<String> tfT12;
    private javax.swing.JComboBox<String> tfT13;
    private javax.swing.JComboBox<String> tfT14;
    private javax.swing.JComboBox<String> tfT15;
    private javax.swing.JComboBox<String> tfT16;
    private javax.swing.JComboBox<String> tfT17;
    private javax.swing.JComboBox<String> tfT18;
    private javax.swing.JComboBox<String> tfT19;
    private javax.swing.JComboBox<String> tfT2;
    private javax.swing.JComboBox<String> tfT20;
    private javax.swing.JComboBox<String> tfT21;
    private javax.swing.JComboBox<String> tfT22;
    private javax.swing.JComboBox<String> tfT23;
    private javax.swing.JComboBox<String> tfT24;
    private javax.swing.JComboBox<String> tfT25;
    private javax.swing.JComboBox<String> tfT26;
    private javax.swing.JComboBox<String> tfT27;
    private javax.swing.JComboBox<String> tfT28;
    private javax.swing.JComboBox<String> tfT29;
    private javax.swing.JComboBox<String> tfT3;
    private javax.swing.JComboBox<String> tfT30;
    private javax.swing.JComboBox<String> tfT31;
    private javax.swing.JComboBox<String> tfT32;
    private javax.swing.JComboBox<String> tfT33;
    private javax.swing.JComboBox<String> tfT34;
    private javax.swing.JComboBox<String> tfT35;
    private javax.swing.JComboBox<String> tfT36;
    private javax.swing.JComboBox<String> tfT37;
    private javax.swing.JComboBox<String> tfT38;
    private javax.swing.JComboBox<String> tfT39;
    private javax.swing.JComboBox<String> tfT4;
    private javax.swing.JComboBox<String> tfT40;
    private javax.swing.JComboBox<String> tfT41;
    private javax.swing.JComboBox<String> tfT42;
    private javax.swing.JComboBox<String> tfT5;
    private javax.swing.JComboBox<String> tfT6;
    private javax.swing.JComboBox<String> tfT7;
    private javax.swing.JComboBox<String> tfT8;
    private javax.swing.JComboBox<String> tfT9;
    // End of variables declaration//GEN-END:variables
    private java.sql.Connection con;
    private java.sql.Statement stmt;
    private java.sql.Statement stmtNavegar;
    private java.sql.ResultSet rsNavegar;
    private dao.FichasDao fichasDao;
    private dao.TreinosDao treinosDao;
    
    private void iniciarBD() {
        
        
        try {
            fichasDao = new FichasDao();
            treinosDao = new TreinosDao();
        } catch ( Exception e ) {
            JOptionPane.showMessageDialog( this, "Erro: " + e.getMessage() );
        }
    }
   public void mostrarDados( Fichas fichas ) throws SQLException {
        tfCod.setText( String.valueOf( fichas.getCod() ) );
        tfNome.setText( String.valueOf( fichas.getNome() ) );
        tfPeso.setText( String.valueOf( fichas.getPeso() ) );
        tfGordura.setText( String.valueOf( fichas.getGordura() ) );
        tfMassa.setText( String.valueOf( fichas.getMassa() ) );
        tfInstrutor.setText( String.valueOf( fichas.getInstrutor() ) );
        tfData.setText( String.valueOf( fichas.getData() ) );
        tfR1.setText( String.valueOf( fichas.getR1() ) );
        tfR2.setText( String.valueOf( fichas.getR2() ) );
        tfR3.setText( String.valueOf( fichas.getR3() ) );
        tfR4.setText( String.valueOf( fichas.getR4() ) );
        tfR5.setText( String.valueOf( fichas.getR5() ) );
        tfR6.setText( String.valueOf( fichas.getR6() ) );
        tfR7.setText( String.valueOf( fichas.getR7() ) );
        tfR8.setText( String.valueOf( fichas.getR8() ) );
        tfR9.setText( String.valueOf( fichas.getR9() ) );
        tfR10.setText( String.valueOf( fichas.getR10() ) );
        tfR11.setText( String.valueOf( fichas.getR11() ) );
        tfR12.setText( String.valueOf( fichas.getR12() ) );
        tfR13.setText( String.valueOf( fichas.getR13() ) );
        tfR14.setText( String.valueOf( fichas.getR14() ) );
        tfR15.setText( String.valueOf( fichas.getR15() ) );
        tfR16.setText( String.valueOf( fichas.getR16() ) );
        tfR17.setText( String.valueOf( fichas.getR17() ) );
        tfR18.setText( String.valueOf( fichas.getR18() ) );
        tfR19.setText( String.valueOf( fichas.getR19() ) );
        tfR20.setText( String.valueOf( fichas.getR20() ) );
        tfR21.setText( String.valueOf( fichas.getR21() ) );
        tfR22.setText( String.valueOf( fichas.getR22() ) );
        tfR23.setText( String.valueOf( fichas.getR23() ) );
        tfR24.setText( String.valueOf( fichas.getR24() ) );
        tfR25.setText( String.valueOf( fichas.getR25() ) );
        tfR26.setText( String.valueOf( fichas.getR26() ) );
        tfR27.setText( String.valueOf( fichas.getR27() ) );
        tfR28.setText( String.valueOf( fichas.getR28() ) );
        tfR29.setText( String.valueOf( fichas.getR29() ) );
        tfR30.setText( String.valueOf( fichas.getR30() ) );
        tfR31.setText( String.valueOf( fichas.getR31() ) );
        tfR32.setText( String.valueOf( fichas.getR32() ) );
        tfR33.setText( String.valueOf( fichas.getR33() ) );
        tfR34.setText( String.valueOf( fichas.getR34() ) );
        tfR35.setText( String.valueOf( fichas.getR35() ) );
        tfR36.setText( String.valueOf( fichas.getR36() ) );
        tfR37.setText( String.valueOf( fichas.getR37() ) );
        tfR38.setText( String.valueOf( fichas.getR38() ) );
        tfR39.setText( String.valueOf( fichas.getR39() ) );
        tfR40.setText( String.valueOf( fichas.getR40() ) );
        tfR41.setText( String.valueOf( fichas.getR41() ) );
        tfR42.setText( String.valueOf( fichas.getR42() ) );
        tfS1.setText( String.valueOf( fichas.getS1() ) );
        tfS2.setText( String.valueOf( fichas.getS2() ) );
        tfS3.setText( String.valueOf( fichas.getS3() ) );
        tfS4.setText( String.valueOf( fichas.getS4() ) );
        tfS5.setText( String.valueOf( fichas.getS5() ) );
        tfS6.setText( String.valueOf( fichas.getS6() ) );
        tfS7.setText( String.valueOf( fichas.getS7() ) );
        tfS8.setText( String.valueOf( fichas.getS8() ) );
        tfS9.setText( String.valueOf( fichas.getS9() ) );
        tfS10.setText( String.valueOf( fichas.getS10() ) );
        tfS11.setText( String.valueOf( fichas.getS11() ) );
        tfS12.setText( String.valueOf( fichas.getS12() ) );
        tfS13.setText( String.valueOf( fichas.getS13() ) );
        tfS14.setText( String.valueOf( fichas.getS14() ) );
        tfS15.setText( String.valueOf( fichas.getS15() ) );
        tfS16.setText( String.valueOf( fichas.getS16() ) );
        tfS17.setText( String.valueOf( fichas.getS17() ) );
        tfS18.setText( String.valueOf( fichas.getS18() ) );
        tfS19.setText( String.valueOf( fichas.getS19() ) );
        tfS20.setText( String.valueOf( fichas.getS20() ) );
        tfS21.setText( String.valueOf( fichas.getS21() ) );
        tfS22.setText( String.valueOf( fichas.getS22() ) );
        tfS23.setText( String.valueOf( fichas.getS23() ) );
        tfS24.setText( String.valueOf( fichas.getS24() ) );
        tfS25.setText( String.valueOf( fichas.getS25() ) );
        tfS26.setText( String.valueOf( fichas.getS26() ) );
        tfS27.setText( String.valueOf( fichas.getS27() ) );
        tfS28.setText( String.valueOf( fichas.getS28() ) );
        tfS29.setText( String.valueOf( fichas.getS29() ) );
        tfS30.setText( String.valueOf( fichas.getS30() ) );
        tfS31.setText( String.valueOf( fichas.getS31() ) );
        tfS32.setText( String.valueOf( fichas.getS32() ) );
        tfS33.setText( String.valueOf( fichas.getS33() ) );
        tfS34.setText( String.valueOf( fichas.getS34() ) );
        tfS35.setText( String.valueOf( fichas.getS35() ) );
        tfS36.setText( String.valueOf( fichas.getS36() ) );
        tfS37.setText( String.valueOf( fichas.getS37() ) );
        tfS38.setText( String.valueOf( fichas.getS38() ) );
        tfS39.setText( String.valueOf( fichas.getS39() ) );
        tfS40.setText( String.valueOf( fichas.getS40() ) );
        tfS41.setText( String.valueOf( fichas.getS41() ) );
        tfS42.setText( String.valueOf( fichas.getS42() ) );
        
        String nomeTreinos1 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT1() );
                if ( nomeTreinos1.equals ( "" )) {
                    nomeTreinos1 = "Treino não Cadastrado";
                }
                tfT1.setSelectedItem( nomeTreinos1 );
                
                String nomeTreinos2 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT2() );
                if ( nomeTreinos2.equals ( "" )) {
                    nomeTreinos2 = "Treino não Cadastrado";
                }
                tfT2.setSelectedItem( nomeTreinos2 );
                
                String nomeTreinos3 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT3() );
                if ( nomeTreinos3.equals ( "" )) {
                    nomeTreinos3 = "Treino não Cadastrado";
                }
                tfT3.setSelectedItem( nomeTreinos3 );
                
                String nomeTreinos4 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT4() );
                if ( nomeTreinos4.equals ( "" )) {
                    nomeTreinos4 = "Treino não Cadastrado";
                }
                tfT4.setSelectedItem( nomeTreinos4 );
                
                String nomeTreinos5 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT5() );
                if ( nomeTreinos5.equals ( "" )) {
                    nomeTreinos5 = "Treino não Cadastrado";
                }
                tfT5.setSelectedItem( nomeTreinos5 );
                
                String nomeTreinos6 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT6() );
                if ( nomeTreinos6.equals ( "" )) {
                    nomeTreinos6 = "Treino não Cadastrado";
                }
                tfT6.setSelectedItem( nomeTreinos6 );
                
                String nomeTreinos7 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT7() );
                if ( nomeTreinos7.equals ( "" )) {
                    nomeTreinos7 = "Treino não Cadastrado";
                }
                tfT7.setSelectedItem( nomeTreinos7 );
                
                String nomeTreinos8 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT8() );
                if ( nomeTreinos8.equals ( "" )) {
                    nomeTreinos8 = "Treino não Cadastrado";
                }
                tfT8.setSelectedItem( nomeTreinos8 );
                
                String nomeTreinos9 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT9() );
                if ( nomeTreinos9.equals ( "" )) {
                    nomeTreinos9 = "Treino não Cadastrado";
                }
                tfT9.setSelectedItem( nomeTreinos9 );
                
                String nomeTreinos10 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT10() );
                if ( nomeTreinos10.equals ( "" )) {
                    nomeTreinos10 = "Treino não Cadastrado";
                }
                tfT10.setSelectedItem( nomeTreinos10 );
                
                String nomeTreinos11 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT11() );
                if ( nomeTreinos11.equals ( "" )) {
                    nomeTreinos11 = "Treino não Cadastrado";
                }
                tfT11.setSelectedItem( nomeTreinos11 );
                
                String nomeTreinos12 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT12() );
                if ( nomeTreinos12.equals ( "" )) {
                    nomeTreinos12 = "Treino não Cadastrado";
                }
                tfT12.setSelectedItem( nomeTreinos12 );
                
                String nomeTreinos13 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT13() );
                if ( nomeTreinos13.equals ( "" )) {
                    nomeTreinos13 = "Treino não Cadastrado";
                }
                tfT13.setSelectedItem( nomeTreinos13 );
                
                String nomeTreinos14 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT14() );
                if ( nomeTreinos14.equals ( "" )) {
                    nomeTreinos14 = "Treino não Cadastrado";
                }
                tfT14.setSelectedItem( nomeTreinos14 );
                
                String nomeTreinos15 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT15() );
                if ( nomeTreinos15.equals ( "" )) {
                    nomeTreinos15 = "Treino não Cadastrado";
                }
                tfT15.setSelectedItem( nomeTreinos15 );
                
                String nomeTreinos16 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT16() );
                if ( nomeTreinos16.equals ( "" )) {
                    nomeTreinos16 = "Treino não Cadastrado";
                }
                tfT16.setSelectedItem( nomeTreinos16 );
                
                String nomeTreinos17 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT17() );
                if ( nomeTreinos17.equals ( "" )) {
                    nomeTreinos17 = "Treino não Cadastrado";
                }
                tfT17.setSelectedItem( nomeTreinos17 );
                
                String nomeTreinos18 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT18() );
                if ( nomeTreinos18.equals ( "" )) {
                    nomeTreinos18 = "Treino não Cadastrado";
                }
                tfT18.setSelectedItem( nomeTreinos18 );
                
                String nomeTreinos19 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT19() );
                if ( nomeTreinos19.equals ( "" )) {
                    nomeTreinos19 = "Treino não Cadastrado";
                }
                tfT19.setSelectedItem( nomeTreinos19 );
                
                String nomeTreinos20 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT20() );
                if ( nomeTreinos20.equals ( "" )) {
                    nomeTreinos20 = "Treino não Cadastrado";
                }
                tfT20.setSelectedItem( nomeTreinos20 );
                String nomeTreinos21 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT21() );
                if ( nomeTreinos21.equals ( "" )) {
                    nomeTreinos21 = "Treino não Cadastrado";
                }
                tfT21.setSelectedItem( nomeTreinos21 );
                String nomeTreinos22 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT22() );
                if ( nomeTreinos22.equals ( "" )) {
                    nomeTreinos22 = "Treino não Cadastrado";
                }
                tfT22.setSelectedItem( nomeTreinos22 );
                String nomeTreinos23 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT23() );
                if ( nomeTreinos23.equals ( "" )) {
                    nomeTreinos23 = "Treino não Cadastrado";
                }
                tfT23.setSelectedItem( nomeTreinos23 );
                String nomeTreinos24 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT24() );
                if ( nomeTreinos24.equals ( "" )) {
                    nomeTreinos24 = "Treino não Cadastrado";
                }
                tfT24.setSelectedItem( nomeTreinos24 );
                String nomeTreinos25 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT25() );
                if ( nomeTreinos25.equals ( "" )) {
                    nomeTreinos25 = "Treino não Cadastrado";
                }
                tfT25.setSelectedItem( nomeTreinos25 );
                String nomeTreinos26 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT26() );
                if ( nomeTreinos26.equals ( "" )) {
                    nomeTreinos26 = "Treino não Cadastrado";
                }
                tfT26.setSelectedItem( nomeTreinos26 );
                String nomeTreinos27 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT27() );
                if ( nomeTreinos27.equals ( "" )) {
                    nomeTreinos27 = "Treino não Cadastrado";
                }
                tfT27.setSelectedItem( nomeTreinos27 );
                String nomeTreinos28 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT28() );
                if ( nomeTreinos28.equals ( "" )) {
                    nomeTreinos28 = "Treino não Cadastrado";
                }
                tfT28.setSelectedItem( nomeTreinos28 );
                String nomeTreinos29 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT29() );
                if ( nomeTreinos29.equals ( "" )) {
                    nomeTreinos29 = "Treino não Cadastrado";
                }
                tfT29.setSelectedItem( nomeTreinos29 );
                
                String nomeTreinos30 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT30() );
                if ( nomeTreinos30.equals ( "" )) {
                    nomeTreinos30 = "Treino não Cadastrado";
                }
                tfT30.setSelectedItem( nomeTreinos30 );
                
                String nomeTreinos31 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT31() );
                if ( nomeTreinos31.equals ( "" )) {
                    nomeTreinos31 = "Treino não Cadastrado";
                }
                tfT31.setSelectedItem( nomeTreinos31 );
                
                String nomeTreinos32 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT32() );
                if ( nomeTreinos32.equals ( "" )) {
                    nomeTreinos32 = "Treino não Cadastrado";
                }
                tfT32.setSelectedItem( nomeTreinos32 );
                
                String nomeTreinos33 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT33() );
                if ( nomeTreinos33.equals ( "" )) {
                    nomeTreinos33 = "Treino não Cadastrado";
                }
                tfT33.setSelectedItem( nomeTreinos33 );
                
                String nomeTreinos34 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT34() );
                if ( nomeTreinos34.equals ( "" )) {
                    nomeTreinos34 = "Treino não Cadastrado";
                }
                tfT34.setSelectedItem( nomeTreinos34 );
                
                String nomeTreinos35 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT35() );
                if ( nomeTreinos35.equals ( "" )) {
                    nomeTreinos35 = "Treino não Cadastrado";
                }
                tfT35.setSelectedItem( nomeTreinos35 );
                
                String nomeTreinos36 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT36() );
                if ( nomeTreinos36.equals ( "" )) {
                    nomeTreinos36 = "Treino não Cadastrado";
                }
                tfT36.setSelectedItem( nomeTreinos36 );
                
                String nomeTreinos37 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT37() );
                if ( nomeTreinos37.equals ( "" )) {
                    nomeTreinos37 = "Treino não Cadastrado";
                }
                tfT37.setSelectedItem( nomeTreinos37 );
                
                String nomeTreinos38 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT38() );
                if ( nomeTreinos38.equals ( "" )) {
                    nomeTreinos38 = "Treino não Cadastrado";
                }
                tfT38.setSelectedItem( nomeTreinos38 );
                
                String nomeTreinos39 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT39() );
                if ( nomeTreinos39.equals ( "" )) {
                    nomeTreinos39 = "Treino não Cadastrado";
                }
                tfT39.setSelectedItem( nomeTreinos39 );
                
                String nomeTreinos40 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT40() );
                if ( nomeTreinos40.equals ( "" )) {
                    nomeTreinos40 = "Treino não Cadastrado";
                }
                tfT40.setSelectedItem( nomeTreinos40 );
                
                String nomeTreinos41 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT41() );
                if ( nomeTreinos41.equals ( "" )) {
                    nomeTreinos41 = "Treino não Cadastrado";
                }
                tfT41.setSelectedItem( nomeTreinos41 );
                
                String nomeTreinos42 = treinosDao.getNomeTreinosByCod( 
                        fichas.getT42() );
                if ( nomeTreinos42.equals ( "" )) {
                    nomeTreinos42 = "Treino não Cadastrado";
                }
                tfT42.setSelectedItem( nomeTreinos42 );
                
    }
    public void primeiro() {
        try {
                Fichas fichas = fichasDao.primeiro();

                if ( fichas != null) {
                    mostrarDados( fichas );
                }                    
            
        } catch ( SQLException e ) {
            JOptionPane.showMessageDialog( this, "Erro: " + e.getMessage() );
        }
    }
    private void montarListaTreinos() {
        
        try {
            List<Treinos> listaTreinos = treinosDao.montarListaTreinos();

            for (Treinos treinos : listaTreinos) {
                tfT1.addItem(treinos.getNome());
                tfT2.addItem(treinos.getNome());
                tfT3.addItem(treinos.getNome());
                tfT4.addItem(treinos.getNome());
                tfT5.addItem(treinos.getNome());
                tfT6.addItem(treinos.getNome());
                tfT7.addItem(treinos.getNome());
                tfT8.addItem(treinos.getNome());
                tfT9.addItem(treinos.getNome());
                tfT10.addItem(treinos.getNome());
                tfT11.addItem(treinos.getNome());
                tfT12.addItem(treinos.getNome());
                tfT13.addItem(treinos.getNome());
                tfT14.addItem(treinos.getNome());
                tfT15.addItem(treinos.getNome());
                tfT16.addItem(treinos.getNome());
                tfT17.addItem(treinos.getNome());
                tfT18.addItem(treinos.getNome());
                tfT19.addItem(treinos.getNome());
                tfT20.addItem(treinos.getNome());
                tfT21.addItem(treinos.getNome());
                tfT22.addItem(treinos.getNome());
                tfT23.addItem(treinos.getNome());
                tfT24.addItem(treinos.getNome());
                tfT25.addItem(treinos.getNome());
                tfT26.addItem(treinos.getNome());
                tfT27.addItem(treinos.getNome());
                tfT28.addItem(treinos.getNome());
                tfT29.addItem(treinos.getNome());
                tfT30.addItem(treinos.getNome());
                tfT31.addItem(treinos.getNome());
                tfT32.addItem(treinos.getNome());
                tfT33.addItem(treinos.getNome());
                tfT34.addItem(treinos.getNome());
                tfT35.addItem(treinos.getNome());
                tfT36.addItem(treinos.getNome());
                tfT37.addItem(treinos.getNome());
                tfT38.addItem(treinos.getNome());
                tfT39.addItem(treinos.getNome());
                tfT40.addItem(treinos.getNome());
                tfT41.addItem(treinos.getNome());
                tfT42.addItem(treinos.getNome());
            }

            tfT1.addItem("Treino não cadastrado");
            tfT2.addItem("Treino não cadastrado");
            tfT3.addItem("Treino não cadastrado");
            tfT4.addItem("Treino não cadastrado");
            tfT5.addItem("Treino não cadastrado");
            tfT6.addItem("Treino não cadastrado");
            tfT7.addItem("Treino não cadastrado");
            tfT8.addItem("Treino não cadastrado");
            tfT9.addItem("Treino não cadastrado");
            tfT10.addItem("Treino não cadastrado");
            tfT11.addItem("Treino não cadastrado");
            tfT12.addItem("Treino não cadastrado");
            tfT13.addItem("Treino não cadastrado");
            tfT14.addItem("Treino não cadastrado");
            tfT15.addItem("Treino não cadastrado");
            tfT16.addItem("Treino não cadastrado");
            tfT17.addItem("Treino não cadastrado");
            tfT18.addItem("Treino não cadastrado");
            tfT19.addItem("Treino não cadastrado");
            tfT20.addItem("Treino não cadastrado");
            tfT21.addItem("Treino não cadastrado");
            tfT22.addItem("Treino não cadastrado");
            tfT23.addItem("Treino não cadastrado");
            tfT24.addItem("Treino não cadastrado");
            tfT25.addItem("Treino não cadastrado");
            tfT26.addItem("Treino não cadastrado");
            tfT27.addItem("Treino não cadastrado");
            tfT28.addItem("Treino não cadastrado");
            tfT29.addItem("Treino não cadastrado");
            tfT30.addItem("Treino não cadastrado");
            tfT31.addItem("Treino não cadastrado");
            tfT32.addItem("Treino não cadastrado");
            tfT33.addItem("Treino não cadastrado");
            tfT34.addItem("Treino não cadastrado");
            tfT35.addItem("Treino não cadastrado");
            tfT36.addItem("Treino não cadastrado");
            tfT37.addItem("Treino não cadastrado");
            tfT38.addItem("Treino não cadastrado");
            tfT39.addItem("Treino não cadastrado");
            tfT40.addItem("Treino não cadastrado");
            tfT41.addItem("Treino não cadastrado");
            tfT42.addItem("Treino não cadastrado");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
        
    }  
  
}

