
package gui;

import dao.UsuariosDao;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class MenuSele extends javax.swing.JFrame {

    /**
     * Creates new form EfetuarLogin
     */
    public MenuSele() {
        initComponents();
        this.addComponentListener(new ComponentAdapter() {

public void componentMoved(ComponentEvent e) {

setEnabled(false);

setEnabled(true);

}

});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jButtonFicha = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        listUsuarios = new javax.swing.JMenuItem();
        listClientes = new javax.swing.JMenuItem();
        listTreinos = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonFicha.setText("Cadastrar Fichas");
        jButtonFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFichaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFicha);
        jButtonFicha.setBounds(220, 110, 150, 27);

        jButton2.setText("Cadastrar Usuarios");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 40, 140, 27);

        jButton3.setText("Cadastrar Clientes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(40, 110, 140, 27);

        jButton4.setText("Cadastrar Treinos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(220, 40, 150, 27);

        jMenu1.setText("Listas");

        listUsuarios.setText("Lista de usuários");
        listUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(listUsuarios);

        listClientes.setText("Lista de clientes");
        listClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listClientesActionPerformed(evt);
            }
        });
        jMenu1.add(listClientes);

        listTreinos.setText("Lista de treinos");
        listTreinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listTreinosActionPerformed(evt);
            }
        });
        jMenu1.add(listTreinos);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFichaActionPerformed
        new GerenciarFichas( this, true ).setVisible( true );
    }//GEN-LAST:event_jButtonFichaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         new CadastrarUsuarios2_1( this, true ).setVisible( true );
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new CadastrarClientes( this, true ).setVisible( true );
    }//GEN-LAST:event_jButton3ActionPerformed

    private void listUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listUsuariosActionPerformed
        new ListUsuarios( this, true ).setVisible( true );
    }//GEN-LAST:event_listUsuariosActionPerformed

    private void listClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listClientesActionPerformed
        new ListClientes( this, true ).setVisible( true );
    }//GEN-LAST:event_listClientesActionPerformed

    private void listTreinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listTreinosActionPerformed
        new ListTreinos( this, true ).setVisible( true );
    }//GEN-LAST:event_listTreinosActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new CadastrarTreinos( this, true ).setVisible( true );
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSele().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonFicha;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem listClientes;
    private javax.swing.JMenuItem listTreinos;
    private javax.swing.JMenuItem listUsuarios;
    // End of variables declaration//GEN-END:variables

}
